CHECKPOINT
GO
DBCC FREEPROCCACHE ('ALL') 
GO
DBCC FREESESSIONCACHE
GO
DBCC DROPCLEANBUFFERS;
GO
DBCC SHRINKFILE (tempdev1, TRUNCATEONLY)
GO
DBCC SHRINKFILE (tempdev2, TRUNCATEONLY)
GO
DBCC SHRINKFILE (tempdev3, TRUNCATEONLY)
GO
DBCC SHRINKFILE (tempdev, TRUNCATEONLY)
GO